# Generated by Django 2.2.11 on 2020-03-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empresa', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Site', models.CharField(max_length=30)),
                ('Rua', models.CharField(max_length=30)),
                ('Bairro', models.CharField(max_length=30)),
                ('Cidade', models.CharField(max_length=30)),
                ('Estado', models.CharField(max_length=30)),
            ],
        ),
    ]
