# Generated by Django 2.2.11 on 2020-03-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='CEP',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastro',
            name='CNPJ',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
