# Generated by Django 2.2.11 on 2020-03-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0003_cadastro_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='pub_date',
            new_name='Data',
        ),
    ]
