# Generated by Django 2.2.11 on 2020-03-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_auto_20200321_0038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='DataRegistro',
        ),
    ]
